-- Script to populate US States and Major Cities
-- This script populates the states and cities tables with US data
-- Note: USA must already exist in the countries table with the correct UUID

-- First, get the USA country_id (adjust this if the UUID is different)
WITH usa_country AS (
  SELECT id as country_id FROM countries WHERE name = 'United States'
)
INSERT INTO states (country_id, name, code, status)
SELECT usa_country.country_id, state_name, state_code, 'active'
FROM usa_country,
(VALUES
  ('Alabama', 'AL'),
  ('Alaska', 'AK'),
  ('Arizona', 'AZ'),
  ('Arkansas', 'AR'),
  ('California', 'CA'),
  ('Colorado', 'CO'),
  ('Connecticut', 'CT'),
  ('Delaware', 'DE'),
  ('Florida', 'FL'),
  ('Georgia', 'GA'),
  ('Hawaii', 'HI'),
  ('Idaho', 'ID'),
  ('Illinois', 'IL'),
  ('Indiana', 'IN'),
  ('Iowa', 'IA'),
  ('Kansas', 'KS'),
  ('Kentucky', 'KY'),
  ('Louisiana', 'LA'),
  ('Maine', 'ME'),
  ('Maryland', 'MD'),
  ('Massachusetts', 'MA'),
  ('Michigan', 'MI'),
  ('Minnesota', 'MN'),
  ('Mississippi', 'MS'),
  ('Missouri', 'MO'),
  ('Montana', 'MT'),
  ('Nebraska', 'NE'),
  ('Nevada', 'NV'),
  ('New Hampshire', 'NH'),
  ('New Jersey', 'NJ'),
  ('New Mexico', 'NM'),
  ('New York', 'NY'),
  ('North Carolina', 'NC'),
  ('North Dakota', 'ND'),
  ('Ohio', 'OH'),
  ('Oklahoma', 'OK'),
  ('Oregon', 'OR'),
  ('Pennsylvania', 'PA'),
  ('Rhode Island', 'RI'),
  ('South Carolina', 'SC'),
  ('South Dakota', 'SD'),
  ('Tennessee', 'TN'),
  ('Texas', 'TX'),
  ('Utah', 'UT'),
  ('Vermont', 'VT'),
  ('Virginia', 'VA'),
  ('Washington', 'WA'),
  ('West Virginia', 'WV'),
  ('Wisconsin', 'WI'),
  ('Wyoming', 'WY'),
  ('District of Columbia', 'DC')
) AS states_data(state_name, state_code)
ON CONFLICT (country_id, name) DO NOTHING;

-- Now insert major cities for each state
-- This uses a CTE to match state_id with state names
INSERT INTO cities (state_id, name, status)
SELECT s.id, city_name, 'active'
FROM states s
JOIN (VALUES
  -- Alabama
  ('Alabama', 'Birmingham'),
  ('Alabama', 'Montgomery'),
  ('Alabama', 'Mobile'),
  ('Alabama', 'Huntsville'),
  ('Alabama', 'Tuscaloosa'),
  -- Alaska
  ('Alaska', 'Anchorage'),
  ('Alaska', 'Juneau'),
  ('Alaska', 'Fairbanks'),
  ('Alaska', 'Ketchikan'),
  ('Alaska', 'Sitka'),
  -- Arizona
  ('Arizona', 'Phoenix'),
  ('Arizona', 'Mesa'),
  ('Arizona', 'Chandler'),
  ('Arizona', 'Scottsdale'),
  ('Arizona', 'Glendale'),
  ('Arizona', 'Tucson'),
  ('Arizona', 'Gilbert'),
  ('Arizona', 'Tempe'),
  ('Arizona', 'Peoria'),
  ('Arizona', 'Surprise'),
  -- Arkansas
  ('Arkansas', 'Little Rock'),
  ('Arkansas', 'Fayetteville'),
  ('Arkansas', 'North Little Rock'),
  ('Arkansas', 'Jonesboro'),
  ('Arkansas', 'Springdale'),
  -- California
  ('California', 'Los Angeles'),
  ('California', 'San Diego'),
  ('California', 'San Jose'),
  ('California', 'San Francisco'),
  ('California', 'Fresno'),
  ('California', 'Sacramento'),
  ('California', 'Long Beach'),
  ('California', 'Oakland'),
  ('California', 'Bakersfield'),
  ('California', 'Anaheim'),
  ('California', 'Santa Ana'),
  ('California', 'Riverside'),
  ('California', 'Stockton'),
  ('California', 'Irvine'),
  ('California', 'Chula Vista'),
  -- Colorado
  ('Colorado', 'Denver'),
  ('Colorado', 'Aurora'),
  ('Colorado', 'Colorado Springs'),
  ('Colorado', 'Fort Collins'),
  ('Colorado', 'Lakewood'),
  ('Colorado', 'Thornton'),
  ('Colorado', 'Pueblo'),
  ('Colorado', 'Arvada'),
  ('Colorado', 'Boulder'),
  ('Colorado', 'Greeley'),
  -- Connecticut
  ('Connecticut', 'Bridgeport'),
  ('Connecticut', 'New Haven'),
  ('Connecticut', 'Hartford'),
  ('Connecticut', 'Waterbury'),
  ('Connecticut', 'Stamford'),
  ('Connecticut', 'Norwalk'),
  ('Connecticut', 'Danbury'),
  ('Connecticut', 'New Britain'),
  ('Connecticut', 'West Hartford'),
  ('Connecticut', 'Greenwich'),
  -- Delaware
  ('Delaware', 'Wilmington'),
  ('Delaware', 'Dover'),
  ('Delaware', 'Newark'),
  ('Delaware', 'Middletown'),
  ('Delaware', 'Smyrna'),
  -- Florida
  ('Florida', 'Jacksonville'),
  ('Florida', 'Miami'),
  ('Florida', 'Tampa'),
  ('Florida', 'Orlando'),
  ('Florida', 'St. Petersburg'),
  ('Florida', 'Hialeah'),
  ('Florida', 'Fort Lauderdale'),
  ('Florida', 'Tallahassee'),
  ('Florida', 'Port St. Lucie'),
  ('Florida', 'Cape Coral'),
  ('Florida', 'Fort Myers'),
  ('Florida', 'Clearwater'),
  ('Florida', 'Daytona Beach'),
  ('Florida', 'Lakeland'),
  ('Florida', 'Coral Springs'),
  -- Georgia
  ('Georgia', 'Atlanta'),
  ('Georgia', 'Augusta'),
  ('Georgia', 'Columbus'),
  ('Georgia', 'Savannah'),
  ('Georgia', 'Alpharetta'),
  ('Georgia', 'Roswell'),
  ('Georgia', 'Johns Creek'),
  ('Georgia', 'Marietta'),
  ('Georgia', 'Macon'),
  ('Georgia', 'Sandy Springs'),
  -- Hawaii
  ('Hawaii', 'Honolulu'),
  ('Hawaii', 'Pearl City'),
  ('Hawaii', 'Kailua'),
  ('Hawaii', 'Kaneohe'),
  ('Hawaii', 'Waipahu'),
  -- Idaho
  ('Idaho', 'Boise'),
  ('Idaho', 'Meridian'),
  ('Idaho', 'Nampa'),
  ('Idaho', 'Idaho Falls'),
  ('Idaho', 'Pocatello'),
  ('Idaho', 'Caldwell'),
  ('Idaho', 'Coeur d''Alene'),
  ('Idaho', 'Lewiston'),
  ('Idaho', 'Moscow'),
  ('Idaho', 'Twin Falls'),
  -- Illinois
  ('Illinois', 'Chicago'),
  ('Illinois', 'Aurora'),
  ('Illinois', 'Rockford'),
  ('Illinois', 'Joliet'),
  ('Illinois', 'Naperville'),
  ('Illinois', 'Springfield'),
  ('Illinois', 'Peoria'),
  ('Illinois', 'Elgin'),
  ('Illinois', 'Evanston'),
  ('Illinois', 'Champaign'),
  ('Illinois', 'Decatur'),
  ('Illinois', 'Schaumburg'),
  ('Illinois', 'Oak Lawn'),
  ('Illinois', 'Cicero'),
  ('Illinois', 'Arlington Heights'),
  -- Indiana
  ('Indiana', 'Indianapolis'),
  ('Indiana', 'Fort Wayne'),
  ('Indiana', 'Evansville'),
  ('Indiana', 'South Bend'),
  ('Indiana', 'Carmel'),
  ('Indiana', 'Bloomington'),
  ('Indiana', 'Fishers'),
  ('Indiana', 'Lafayette'),
  ('Indiana', 'Terre Haute'),
  ('Indiana', 'Muncie'),
  -- Iowa
  ('Iowa', 'Des Moines'),
  ('Iowa', 'Cedar Rapids'),
  ('Iowa', 'Davenport'),
  ('Iowa', 'Sioux City'),
  ('Iowa', 'Iowa City'),
  ('Iowa', 'Council Bluffs'),
  ('Iowa', 'Waterloo'),
  ('Iowa', 'Dubuque'),
  ('Iowa', 'Ames'),
  ('Iowa', 'West Des Moines'),
  -- Kansas
  ('Kansas', 'Kansas City'),
  ('Kansas', 'Wichita'),
  ('Kansas', 'Overland Park'),
  ('Kansas', 'Topeka'),
  ('Kansas', 'Olathe'),
  ('Kansas', 'Lawrence'),
  ('Kansas', 'Shawnee'),
  ('Kansas', 'Lenexa'),
  ('Kansas', 'Manhattan'),
  ('Kansas', 'Salina'),
  -- Kentucky
  ('Kentucky', 'Louisville'),
  ('Kentucky', 'Lexington'),
  ('Kentucky', 'Bowling Green'),
  ('Kentucky', 'Owensboro'),
  ('Kentucky', 'Covington'),
  ('Kentucky', 'Hopkinsville'),
  ('Kentucky', 'Richmond'),
  ('Kentucky', 'Frankfort'),
  ('Kentucky', 'Paducah'),
  ('Kentucky', 'Florence'),
  -- Louisiana
  ('Louisiana', 'New Orleans'),
  ('Louisiana', 'Baton Rouge'),
  ('Louisiana', 'Shreveport'),
  ('Louisiana', 'Lafayette'),
  ('Louisiana', 'Lake Charles'),
  ('Louisiana', 'Monroe'),
  ('Louisiana', 'Alexandria'),
  ('Louisiana', 'Metairie'),
  ('Louisiana', 'Kenner'),
  ('Louisiana', 'Houma'),
  -- Maine
  ('Maine', 'Portland'),
  ('Maine', 'Lewiston'),
  ('Maine', 'Bangor'),
  ('Maine', 'Auburn'),
  ('Maine', 'Augusta'),
  ('Maine', 'Westbrook'),
  ('Maine', 'Waterville'),
  ('Maine', 'Biddeford'),
  ('Maine', 'Sanford'),
  ('Maine', 'Presque Isle'),
  -- Maryland
  ('Maryland', 'Baltimore'),
  ('Maryland', 'Columbia'),
  ('Maryland', 'Annapolis'),
  ('Maryland', 'Gaithersburg'),
  ('Maryland', 'Bowie'),
  ('Maryland', 'Frederick'),
  ('Maryland', 'Rockville'),
  ('Maryland', 'Silver Spring'),
  ('Maryland', 'Laurel'),
  ('Maryland', 'Salisbury'),
  -- Massachusetts
  ('Massachusetts', 'Boston'),
  ('Massachusetts', 'Worcester'),
  ('Massachusetts', 'Springfield'),
  ('Massachusetts', 'Lowell'),
  ('Massachusetts', 'Cambridge'),
  ('Massachusetts', 'New Bedford'),
  ('Massachusetts', 'Brockton'),
  ('Massachusetts', 'Quincy'),
  ('Massachusetts', 'Lynn'),
  ('Massachusetts', 'Fall River'),
  -- Michigan
  ('Michigan', 'Detroit'),
  ('Michigan', 'Grand Rapids'),
  ('Michigan', 'Warren'),
  ('Michigan', 'Sterling Heights'),
  ('Michigan', 'Ann Arbor'),
  ('Michigan', 'Lansing'),
  ('Michigan', 'Flint'),
  ('Michigan', 'Dearborn'),
  ('Michigan', 'Livonia'),
  ('Michigan', 'Kalamazoo'),
  -- Minnesota
  ('Minnesota', 'Minneapolis'),
  ('Minnesota', 'Saint Paul'),
  ('Minnesota', 'Rochester'),
  ('Minnesota', 'Bloomington'),
  ('Minnesota', 'Plymouth'),
  ('Minnesota', 'Duluth'),
  ('Minnesota', 'Coon Rapids'),
  ('Minnesota', 'St. Louis Park'),
  ('Minnesota', 'Edina'),
  ('Minnesota', 'Maple Grove'),
  -- Mississippi
  ('Mississippi', 'Jackson'),
  ('Mississippi', 'Gulfport'),
  ('Mississippi', 'Biloxi'),
  ('Mississippi', 'Hattiesburg'),
  ('Mississippi', 'Greenville'),
  ('Mississippi', 'Tupelo'),
  ('Mississippi', 'Meridian'),
  ('Mississippi', 'Vicksburg'),
  ('Mississippi', 'Gautier'),
  ('Mississippi', 'Madison'),
  -- Missouri
  ('Missouri', 'Kansas City'),
  ('Missouri', 'St. Louis'),
  ('Missouri', 'Springfield'),
  ('Missouri', 'Independence'),
  ('Missouri', 'Columbia'),
  ('Missouri', 'Lee''s Summit'),
  ('Missouri', 'Joplin'),
  ('Missouri', 'St. Peters'),
  ('Missouri', 'O''Fallon'),
  ('Missouri', 'Cape Girardeau'),
  -- Montana
  ('Montana', 'Billings'),
  ('Montana', 'Missoula'),
  ('Montana', 'Great Falls'),
  ('Montana', 'Butte'),
  ('Montana', 'Bozeman'),
  ('Montana', 'Helena'),
  ('Montana', 'Kalispell'),
  ('Montana', 'Havre'),
  ('Montana', 'Miles City'),
  ('Montana', 'Anaconda'),
  -- Nebraska
  ('Nebraska', 'Omaha'),
  ('Nebraska', 'Lincoln'),
  ('Nebraska', 'Bellevue'),
  ('Nebraska', 'Grand Island'),
  ('Nebraska', 'Kearney'),
  ('Nebraska', 'Fremont'),
  ('Nebraska', 'Hastings'),
  ('Nebraska', 'North Platte'),
  ('Nebraska', 'Papillion'),
  ('Nebraska', 'Scottsbluff'),
  -- Nevada
  ('Nevada', 'Las Vegas'),
  ('Nevada', 'Henderson'),
  ('Nevada', 'Reno'),
  ('Nevada', 'North Las Vegas'),
  ('Nevada', 'Sparks'),
  ('Nevada', 'Carson City'),
  ('Nevada', 'Elko'),
  ('Nevada', 'Boulder City'),
  ('Nevada', 'Winnemucca'),
  ('Nevada', 'Yerington'),
  -- New Hampshire
  ('New Hampshire', 'Manchester'),
  ('New Hampshire', 'Nashua'),
  ('New Hampshire', 'Concord'),
  ('New Hampshire', 'Rochester'),
  ('New Hampshire', 'Dover'),
  ('New Hampshire', 'Merrimack'),
  ('New Hampshire', 'Derry'),
  ('New Hampshire', 'Keene'),
  ('New Hampshire', 'Laconia'),
  ('New Hampshire', 'Portsmouth'),
  -- New Jersey
  ('New Jersey', 'Newark'),
  ('New Jersey', 'Jersey City'),
  ('New Jersey', 'Paterson'),
  ('New Jersey', 'Elizabeth'),
  ('New Jersey', 'Trenton'),
  ('New Jersey', 'Clifton'),
  ('New Jersey', 'Camden'),
  ('New Jersey', 'Passaic'),
  ('New Jersey', 'Union'),
  ('New Jersey', 'Vineland'),
  -- New Mexico
  ('New Mexico', 'Albuquerque'),
  ('New Mexico', 'Las Cruces'),
  ('New Mexico', 'Rio Rancho'),
  ('New Mexico', 'Santa Fe'),
  ('New Mexico', 'Roswell'),
  ('New Mexico', 'Clovis'),
  ('New Mexico', 'Carlsbad'),
  ('New Mexico', 'Grants'),
  ('New Mexico', 'Gallup'),
  ('New Mexico', 'Farmington'),
  -- New York
  ('New York', 'New York'),
  ('New York', 'Buffalo'),
  ('New York', 'Rochester'),
  ('New York', 'Yonkers'),
  ('New York', 'New Rochelle'),
  ('New York', 'Syracuse'),
  ('New York', 'Albany'),
  ('New York', 'Mount Vernon'),
  ('New York', 'Schenectady'),
  ('New York', 'Utica'),
  -- North Carolina
  ('North Carolina', 'Charlotte'),
  ('North Carolina', 'Raleigh'),
  ('North Carolina', 'Greensboro'),
  ('North Carolina', 'Durham'),
  ('North Carolina', 'Winston-Salem'),
  ('North Carolina', 'Fayetteville'),
  ('North Carolina', 'Cary'),
  ('North Carolina', 'Wilmington'),
  ('North Carolina', 'High Point'),
  ('North Carolina', 'Greenville'),
  -- North Dakota
  ('North Dakota', 'Bismarck'),
  ('North Dakota', 'Fargo'),
  ('North Dakota', 'Grand Forks'),
  ('North Dakota', 'Minot'),
  ('North Dakota', 'Williston'),
  ('North Dakota', 'Dickinson'),
  ('North Dakota', 'Jamestown'),
  ('North Dakota', 'Mandan'),
  ('North Dakota', 'Valley City'),
  ('North Dakota', 'Wahpeton'),
  -- Ohio
  ('Ohio', 'Columbus'),
  ('Ohio', 'Cleveland'),
  ('Ohio', 'Cincinnati'),
  ('Ohio', 'Toledo'),
  ('Ohio', 'Akron'),
  ('Ohio', 'Dayton'),
  ('Ohio', 'Parma'),
  ('Ohio', 'Canton'),
  ('Ohio', 'Youngstown'),
  ('Ohio', 'Lorain'),
  -- Oklahoma
  ('Oklahoma', 'Oklahoma City'),
  ('Oklahoma', 'Tulsa'),
  ('Oklahoma', 'Norman'),
  ('Oklahoma', 'Broken Arrow'),
  ('Oklahoma', 'Lawton'),
  ('Oklahoma', 'Edmond'),
  ('Oklahoma', 'Moore'),
  ('Oklahoma', 'Midwest City'),
  ('Oklahoma', 'Enid'),
  ('Oklahoma', 'Stillwater'),
  -- Oregon
  ('Oregon', 'Portland'),
  ('Oregon', 'Eugene'),
  ('Oregon', 'Salem'),
  ('Oregon', 'Gresham'),
  ('Oregon', 'Hillsboro'),
  ('Oregon', 'Bend'),
  ('Oregon', 'Medford'),
  ('Oregon', 'Springfield'),
  ('Oregon', 'Corvallis'),
  ('Oregon', 'Grants Pass'),
  -- Pennsylvania
  ('Pennsylvania', 'Philadelphia'),
  ('Pennsylvania', 'Pittsburgh'),
  ('Pennsylvania', 'Allentown'),
  ('Pennsylvania', 'Erie'),
  ('Pennsylvania', 'Reading'),
  ('Pennsylvania', 'Scranton'),
  ('Pennsylvania', 'Bethlehem'),
  ('Pennsylvania', 'Lancaster'),
  ('Pennsylvania', 'Harrisburg'),
  ('Pennsylvania', 'Altoona'),
  -- Rhode Island
  ('Rhode Island', 'Providence'),
  ('Rhode Island', 'Warwick'),
  ('Rhode Island', 'Cranston'),
  ('Rhode Island', 'Pawtucket'),
  ('Rhode Island', 'Woonsocket'),
  ('Rhode Island', 'Newport'),
  ('Rhode Island', 'Central Falls'),
  ('Rhode Island', 'Westerly'),
  ('Rhode Island', 'Coventry'),
  ('Rhode Island', 'Barrington'),
  -- South Carolina
  ('South Carolina', 'Charleston'),
  ('South Carolina', 'Columbia'),
  ('South Carolina', 'Greenville'),
  ('South Carolina', 'Myrtle Beach'),
  ('South Carolina', 'Spartanburg'),
  ('South Carolina', 'Rock Hill'),
  ('South Carolina', 'Florence'),
  ('South Carolina', 'Summerville'),
  ('South Carolina', 'Goose Creek'),
  ('South Carolina', 'Hilton Head Island'),
  -- South Dakota
  ('South Dakota', 'Sioux Falls'),
  ('South Dakota', 'Rapid City'),
  ('South Dakota', 'Aberdeen'),
  ('South Dakota', 'Watertown'),
  ('South Dakota', 'Mitchell'),
  ('South Dakota', 'Yankton'),
  ('South Dakota', 'Pierre'),
  ('South Dakota', 'Brookings'),
  ('South Dakota', 'Spearfish'),
  ('South Dakota', 'Huron'),
  -- Tennessee
  ('Tennessee', 'Memphis'),
  ('Tennessee', 'Nashville'),
  ('Tennessee', 'Knoxville'),
  ('Tennessee', 'Chattanooga'),
  ('Tennessee', 'Clarksville'),
  ('Tennessee', 'Murfreesboro'),
  ('Tennessee', 'Franklin'),
  ('Tennessee', 'Jackson'),
  ('Tennessee', 'Johnson City'),
  ('Tennessee', 'Kingsport'),
  -- Texas
  ('Texas', 'Houston'),
  ('Texas', 'San Antonio'),
  ('Texas', 'Dallas'),
  ('Texas', 'Austin'),
  ('Texas', 'Fort Worth'),
  ('Texas', 'El Paso'),
  ('Texas', 'Arlington'),
  ('Texas', 'Corpus Christi'),
  ('Texas', 'Lubbock'),
  ('Texas', 'Laredo'),
  ('Texas', 'Irving'),
  ('Texas', 'Garland'),
  ('Texas', 'Plano'),
  ('Texas', 'Amarillo'),
  ('Texas', 'Brownsville'),
  -- Utah
  ('Utah', 'Salt Lake City'),
  ('Utah', 'West Valley City'),
  ('Utah', 'Provo'),
  ('Utah', 'West Jordan'),
  ('Utah', 'Sandy'),
  ('Utah', 'Ogden'),
  ('Utah', 'Orem'),
  ('Utah', 'Layton'),
  ('Utah', 'Lehi'),
  ('Utah', 'Taylorsville'),
  -- Vermont
  ('Vermont', 'Burlington'),
  ('Vermont', 'Rutland'),
  ('Vermont', 'South Burlington'),
  ('Vermont', 'Colchester'),
  ('Vermont', 'Montpelier'),
  ('Vermont', 'Newport'),
  ('Vermont', 'Barre'),
  ('Vermont', 'Winooski'),
  ('Vermont', 'Hartford'),
  ('Vermont', 'Bennington'),
  -- Virginia
  ('Virginia', 'Virginia Beach'),
  ('Virginia', 'Richmond'),
  ('Virginia', 'Arlington'),
  ('Virginia', 'Alexandria'),
  ('Virginia', 'Roanoke'),
  ('Virginia', 'Charlottesville'),
  ('Virginia', 'Blacksburg'),
  ('Virginia', 'Falls Church'),
  ('Virginia', 'Hampton'),
  ('Virginia', 'Newport News'),
  -- Washington
  ('Washington', 'Seattle'),
  ('Washington', 'Spokane'),
  ('Washington', 'Tacoma'),
  ('Washington', 'Vancouver'),
  ('Washington', 'Bellevue'),
  ('Washington', 'Kent'),
  ('Washington', 'Everett'),
  ('Washington', 'Renton'),
  ('Washington', 'Federal Way'),
  ('Washington', 'Yakima'),
  -- West Virginia
  ('West Virginia', 'Charleston'),
  ('West Virginia', 'Huntington'),
  ('West Virginia', 'Parkersburg'),
  ('West Virginia', 'Morgantown'),
  ('West Virginia', 'Wheeling'),
  ('West Virginia', 'Fairmont'),
  ('West Virginia', 'Beckley'),
  ('West Virginia', 'Weirton'),
  ('West Virginia', 'Princeton'),
  ('West Virginia', 'Lewisburg'),
  -- Wisconsin
  ('Wisconsin', 'Milwaukee'),
  ('Wisconsin', 'Madison'),
  ('Wisconsin', 'Green Bay'),
  ('Wisconsin', 'Kenosha'),
  ('Wisconsin', 'Racine'),
  ('Wisconsin', 'Appleton'),
  ('Wisconsin', 'Waukesha'),
  ('Wisconsin', 'Eau Claire'),
  ('Wisconsin', 'Oshkosh'),
  ('Wisconsin', 'Janesville'),
  -- Wyoming
  ('Wyoming', 'Cheyenne'),
  ('Wyoming', 'Casper'),
  ('Wyoming', 'Laramie'),
  ('Wyoming', 'Gillette'),
  ('Wyoming', 'Rock Springs'),
  ('Wyoming', 'Sheridan'),
  ('Wyoming', 'Riverton'),
  ('Wyoming', 'Jackson'),
  ('Wyoming', 'Powell'),
  ('Wyoming', 'Cody'),
  -- District of Columbia
  ('District of Columbia', 'Washington')
) AS cities_data(state_name, city_name) ON s.name = cities_data.state_name
ON CONFLICT (state_id, name) DO NOTHING;
