-- DEPRECATED: Admin Users Sync Script
-- This migration script is no longer needed.
-- The admin_users table has been eliminated and replaced with a role-based system.
-- All user data, including admin/moderator users, is now stored in the profiles table.
--
-- Admin/moderator users are identified by their role_id foreign key reference in profiles:
-- SELECT p.* FROM profiles p 
-- INNER JOIN roles r ON p.role_id = r.id 
-- WHERE r.role_name IN ('admin', 'moderator');

-- No action required - this script is kept for historical reference only.
